// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6vlE0vFylHnTcPieQ6-bUK9wQ7b5Bv7w',
    appId: '1:248694754665:web:4cfa9f25ea3f5a052881f8',
    messagingSenderId: '248694754665',
    projectId: 'eventserviceapp-6ff7a',
    authDomain: 'eventserviceapp-6ff7a.firebaseapp.com',
    storageBucket: 'eventserviceapp-6ff7a.firebasestorage.app',
    measurementId: 'G-0D8VEVQGC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjlkHSZ2SnoXuMiAmzzCe_Z1L99rsATek',
    appId: '1:248694754665:android:649865d398778acd2881f8',
    messagingSenderId: '248694754665',
    projectId: 'eventserviceapp-6ff7a',
    storageBucket: 'eventserviceapp-6ff7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmkjhflNwIlPm8NQqiaqWBGj24yujC_Lg',
    appId: '1:248694754665:ios:3d9878a7a44d3b232881f8',
    messagingSenderId: '248694754665',
    projectId: 'eventserviceapp-6ff7a',
    storageBucket: 'eventserviceapp-6ff7a.firebasestorage.app',
    iosBundleId: 'com.example.eventServiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmkjhflNwIlPm8NQqiaqWBGj24yujC_Lg',
    appId: '1:248694754665:ios:3d9878a7a44d3b232881f8',
    messagingSenderId: '248694754665',
    projectId: 'eventserviceapp-6ff7a',
    storageBucket: 'eventserviceapp-6ff7a.firebasestorage.app',
    iosBundleId: 'com.example.eventServiceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6vlE0vFylHnTcPieQ6-bUK9wQ7b5Bv7w',
    appId: '1:248694754665:web:94c17d3620db3f6f2881f8',
    messagingSenderId: '248694754665',
    projectId: 'eventserviceapp-6ff7a',
    authDomain: 'eventserviceapp-6ff7a.firebaseapp.com',
    storageBucket: 'eventserviceapp-6ff7a.firebasestorage.app',
    measurementId: 'G-LWZC2RP6ME',
  );
}
